title: "Jason Jung"
description: "Welcome to my website"
theme: minima
markdown: kramdown


header_pages:
  - about.md
  - HWprojects.md
  - SWprojects.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: light        # options: light, dark
  logo: "/assets/profile.jpg"
  social_links:
    linkedin: "https://www.linkedin.com/in/jason-jung-b6b2931b3/"


