title: "Your Name"
description: "My personal website"
theme: minima

# Sidebar options
author:
  name: Your Name
  avatar: "/assets/profile.jpg"
  bio: "Hi, I'm Jason Jung"

# Navigation
header_pages:
  - about.md
  - projects.md

# Social links (optional)
github_username: your-username
linkedin_username: your-linkedin
