title: "Jason Jung"
description: "My personal website"
theme: jekyll-theme-minimal
logo: "/assets/profile.jpg"

# Sidebar options
author:
  name: Jason Jung
  avatar: "/assets/profile.jpg"
  bio: "Hi, I'm Jason Jung"

# Navigation
header_pages:
  - about.md
  - projects.md

# Social links (optional)
github_username: JasonDJung
linkedin_username: https://www.linkedin.com/in/jason-jung-b6b2931b3/
